apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
      - name: hello-app
        image: python:3.9-slim
        command: ["sh", "-c"]
        args:
          - |
            pip install flask && \
            python -c "
            from flask import Flask, render_template_string
            app = Flask(__name__)
            html = '''
            <!DOCTYPE html>
            <html>
            <head>
                <title>Hello App</title>
                <script>
                    window.onload = function() {
                        let name = prompt('Enter your name:');
                        if(name) {
                            document.getElementById('greet').innerText = 'Hello from v2' + name + '!';
                        }
                    }
                </script>
            </head>
            <body>
                <h1 id='greet'>Welcome!</h1>
            </body>
            </html>
            '''
            @app.route('/')
            def home():
                return render_template_string(html)
            app.run(host='0.0.0.0', port=5000)
            "
        ports:
          - containerPort: 5000
